Include PDF v2.0
kreativmonkey/pandoc-wbh-template pull request #24
Opened 2021-11-04 18:38 UTC by aslmx

This PR introduces the ability to fill the Header fields of the WBH assignments.

There were quite some changes necessary

beispiel.md markdown
change: replace name by firstname + lastname - it should be backwards compatible (see wbh.tex)
cahnge: added various variables to control the behaviour, see README.md

wbh.tex: 
+ a variable `\studentname` that is either `student.name` if it is set (for backwards compatibility) or `student.firstname + student.lastname`
+ a function that includes and fills the PDF with the information from the YAML in the markdown document
changed: replaced `student.name` by `\studentname` where necessary. It is assumed that either `student.name`or `student.firstname + student.lastname` are set, so that `\studentname` should always have a value. Hence I removed checks for its existence, because it should exist.
cahnged: I had to change some paddings on the title page, so that it would not break into two pages when the students address was set 

README.md:
+ explanations
changed: example

Meta:
changed: Aufgabenstellung.odt, moved to Beispiel/Aufgabenstellung where it should belong (was in the repo root). Added an example form with approximate positioning, so that the example can be used to showcase the form filling

beispiel.tex and beispiel.pdf are also updated.

Tested quite a lot, hope i covered all the cases. 

**Todo:**
For a potential version 2.1 or 3.0 it could be adapted to properly support A-Assignments (which do not begin on page 1).

2021-11-12 12:31 UTC, kreativmonkey requested changes
Ich weiß es sieht beim Programmieren scheiße aus, aber ich finde der Generierte LatexCode sollte sauber und nachvollziehbar sein. Dafür ist leider die Vorlage nicht ganz so schön zu lesen... alle if/else von pandoc sind in einer linie zu behandeln. Der Generierte Code soll am ende die Einrückung erhalten die man beim direkten schreiben von Latex machen würde.

2021-11-12 12:31 UTC, kreativmonkey commented on Beispiel/beispiel.tex
> +            }
Bitte nochmal das alignment prüfen

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +    $endif$
Bitte das Alignment überprüfen. Die Pandoc if abfragen müssen in einer linie bleiben denn diese werden in Latexnicht angezeigt. Der generierte Code soll jedoch möglichst sauber aussehen.

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +    \def \studentname{$student.firstname$ $student.lastname$}
alignment

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +    \def \studentname{$student.name$}
alignment

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +                \node at (95,-59) [info] {$studium.studiengangnr$}; % etwas länger länger};
Hier sollten noch if abfragen für die inzelnen attribute gemacht werden. Sonst werden errors geschmissen wenn Attribute nicht gesetzt sind. Ist natürlich die Frage ob man das nicht genau so will...

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +    \def \studentname{$student.firstname$ $student.lastname$}
auch hier noch die Abfrage für $if(student.lastname)$....

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +    $endif$
alignment

2021-11-12 12:31 UTC, kreativmonkey commented on wbh.tex
> +        \assignment
alignment

2021-11-15 19:03 UTC, kreativmonkey requested changes

2021-11-15 19:03 UTC, kreativmonkey commented on Beispiel/beispiel.tex
> +
Evtl. sollten wir das auch optional machen das es ausgefüllt wird? Man könnte dann evtl. noch ein "fillpage" machen oder so, was meinst du?

2021-11-16 06:30 UTC, aslmx commented on Beispiel/beispiel.tex
> +
siehe
wbh.tex Zeile 90, `fillform` wird auf existenz überpüft, sonst wird nix ausgefüllt. 
Btw du kommentierst hier das generierte .tex
Ich sehe aber, dass ich die "etwas länger" Kommentare noch rausnehmen könnte.

2021-11-28 15:18 UTC, kreativmonkey approved these changes

2021-11-28 15:19 UTC, kreativmonkey commented
Sorry there are some conflicts, can you resolve the confilcts and merge please?

2021-12-02 08:43 UTC, merged