Introduce \solution{x} for double underlined solutions of equations
kreativmonkey/pandoc-wbh-template pull request #31
Opened 2021-11-14 10:58 UTC by aslmx

Introduce \solution{x} for double underlined solutions of equations

Changes: 
wbh.tex: added `\solution` as new command for double underlined text in math equations
beispiel.md: added example of usage

2021-11-14 10:59 UTC, aslmx commented
Fixes/Implementes FR in #20

2021-11-15 19:12 UTC, kreativmonkey requested changes

2021-11-15 19:12 UTC, kreativmonkey commented on Beispiel/beispiel.tex
>  % ----------------------------------------------------------------------------------------------------------
Hier scheint was durcheinander gegangen zu sein. Das tex sollte schon mit der Solution generiert werden.

2021-11-16 06:32 UTC, aslmx commented on Beispiel/beispiel.tex
>  % ----------------------------------------------------------------------------------------------------------
`\solution{x}` generiert innerhalb von equations einen doppelt unterstrichenen Text. Ich denke das ist doch genau das gewesen was du wolltest :thinking:
Können wir nochmal klären.

2021-11-17 17:18 UTC, kreativmonkey commented on Beispiel/beispiel.tex
>  % ----------------------------------------------------------------------------------------------------------
Das ist richtig. Ich wollte nur das du die beispiel.tex auch mit der version übersetzt ;-)

2021-12-02 09:21 UTC, merged