added else branch, that adds the $ in case logo is not set
kreativmonkey/pandoc-wbh-template pull request #32
Opened 2021-11-14 11:37 UTC by aslmx

changes.
- wbh.tex: added else branch on title page. If logo is not set, $hochschule$ will be used instead
- beispiel.md: added hochschule as variable with comment.

2021-11-14 11:38 UTC, aslmx commented
This could resolve #30

2021-11-15 19:13 UTC, kreativmonkey requested changes

2021-11-15 19:13 UTC, kreativmonkey commented on wbh.tex
> +	\Huge \textbf{$hochschule$} \\
bitte auch die Hochschule "optional" belassen. Also entweder Logo oder Hochschulname oder gar nichts.

2021-11-15 19:15 UTC, kreativmonkey commented on wbh.tex
> +	\Huge \textbf{$hochschule$} \\
achso und natürlich wieder auf die Einrückung achten ;-)

2021-11-16 06:33 UTC, aslmx commented on wbh.tex
> +	\Huge \textbf{$hochschule$} \\
Kriegen wir hin...

2021-11-17 17:14 UTC, aslmx commented on wbh.tex
> +	\Huge \textbf{$hochschule$} \\
Ich hab es jetzt so implementiert wie in README.md beschrieben. 
 Also entweder Logo oder Hochschulname oder gar nichts:

`(Logo XOR Name) XOR garnichts`

2021-11-17 18:33 UTC, kreativmonkey approved these changes

2021-11-17 18:33 UTC, merged